# Generated by Django 2.0.6 on 2019-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(blank=True, max_length=40, null=True)),
                ('receive_address', models.CharField(blank=True, max_length=60, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('tel', models.CharField(blank=True, max_length=40, null=True)),
                ('obligate', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=40, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=40, null=True)),
                ('book_num', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='TDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bbok_name', models.CharField(blank=True, max_length=40, null=True)),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('headpic', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
                ('publish', models.CharField(blank=True, max_length=40, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=40, null=True)),
                ('printtime', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=40, null=True)),
                ('word_num', models.CharField(blank=True, max_length=40, null=True)),
                ('page_num', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=40, null=True)),
                ('pages', models.CharField(blank=True, max_length=40, null=True)),
                ('packing', models.CharField(blank=True, max_length=40, null=True)),
                ('market_price', models.FloatField(blank=True, null=True)),
                ('editer_commend', models.IntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=40, null=True)),
                ('sales', models.CharField(blank=True, max_length=40, null=True)),
                ('dd_price', models.FloatField(blank=True, null=True)),
                ('save', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=60, null=True)),
                ('author_intro', models.CharField(blank=True, max_length=60, null=True)),
                ('catalog', models.CharField(blank=True, max_length=60, null=True)),
                ('media_comment', models.CharField(blank=True, max_length=60, null=True)),
                ('pic_url', models.CharField(blank=True, max_length=40, null=True)),
                ('shelf_time', models.DateField(blank=True, null=True)),
                ('print_num', models.CharField(blank=True, max_length=40, null=True)),
                ('list', models.CharField(blank=True, max_length=10, null=True)),
                ('sore', models.FloatField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=60, null=True)),
                ('obligate', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_detail',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('all_price', models.FloatField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrderitem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('book_count', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_orderitem',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user',
            },
        ),
    ]
