# Generated by Django 2.0.6 on 2019-05-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcategory',
            options={},
        ),
    ]
