# Generated by Django 2.0.6 on 2019-05-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0002_auto_20190516_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
                ('u', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 't_confirmstring',
            },
        ),
        migrations.AlterModelOptions(
            name='tcategory',
            options={'managed': False},
        ),
    ]
